num1 = int(input("enter your first number: "))
num2 = int(input("enter your second number: "))
num3 = int(input("enter your third number: "))
num4 = int(num1+num2+num3)
print("all the numbers you inputted added together makes", num4)
